image: node:14.18.1

stages:
  - lint
  - release

cache:
  paths:
    - node_modules/

include:
  - project: 'dimensional-innovations/ci-cd'
    ref: master
    file: '/javascript/release-package.yml'
  - project: 'dimensional-innovations/ci-cd'
    ref: master
    file: '/javascript/auth-with-di-package-registry.yml'

lint:
  stage: lint
  script:
    - yarn install
    - yarn lint