image: node:14.18.1

stages:
  - build
  - release

cache:
  paths:
    - node_modules/

include:
  - project: 'dimensional-innovations/ci-cd'
    ref: master
    file: '/javascript/auth-with-di-package-registry.yml'
  - project: 'dimensional-innovations/ci-cd'
    ref: master
    file: '/javascript/release-package.yml'

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist/**/*

build_lint:
  stage: build
  script:
    - yarn lint